Finish Unbound podman image

diff --git a/unbound/Dockerfile b/unbound/Dockerfile
--- a/unbound/Dockerfile
+++ b/unbound/Dockerfile
@@ -1,9 +1,9 @@
 FROM docker.io/library/debian:latest
 
-ARG OPENSSL_VERSION=openssl-3.5.0
+ARG OPENSSL_VERSION=3.5.0
 ARG OPENSSL_SHA256=344d0a79f1a9b08029b0744e2cc401a43f9c90acd1044d09a530b4885a8e9fc0
-ARG OPENSSL_DOWNLOAD_URL=https://github.com/openssl/openssl/releases/download/${OPENSSL_VERSION}/${OPENSSL_VERSION}.tar.gz
-ARG OPENSSL_PGP_SIG=https://github.com/openssl/openssl/releases/download/${OPENSSL_VERSION}/${OPENSSL_VERSION}.tar.gz.asc
+ARG OPENSSL_DOWNLOAD_URL=https://github.com/openssl/openssl/releases/download/openssl-${OPENSSL_VERSION}/openssl-${OPENSSL_VERSION}.tar.gz
+ARG OPENSSL_PGP_SIG=https://github.com/openssl/openssl/releases/download/openssl-${OPENSSL_VERSION}/openssl-${OPENSSL_VERSION}.tar.gz.asc
 ARG NAME=unbound
 ARG UNBOUND_VERSION=1.23.0
 ARG UNBOUND_SHA256=959bd5f3875316d7b3f67ee237a56de5565f5b35fc9b5fc3cea6cfe735a03bb8
@@ -13,6 +13,11 @@ ARG SUMMARY="${NAME} is a validating, recursive, and caching DNS resolver."
 ARG DESCRIPTION="${NAME} is a validating, recursive, and caching DNS resolver."
 ARG GROUP_ID=9898
 ARG USER_ID=9898
+ARG OPENSSL_GPG_PUBKEY='BA5473A2B0587B07FB27CF2D216094DFD0CB81EF'
+ARG RICHARD_LEVITTE='7953AC1FBC3DC8B3B292393ED5E9E43F7DF9EE8C'
+ARG MATT_CASWELL='8657ABB260F056B1E5190839D9C4D26D0E604491'
+ARG PAUL_DALE='B7C1C14360F353A36862E4D5231C84CDDCC69C45'
+ARG TOMAS_MRAZ='A21FAB74B0088AA361152586B8EF1A6BA9DA2D5C'
 
 ENV DEBIAN_FRONTEND=noninteractive
 
@@ -22,6 +27,7 @@ RUN set -e -x && apt update && apt upgrade -y && apt install -y \
     build-essential \
     curl \
     ca-certificates \
+    dnsutils \
     gpg \
     dirmngr \
     libidn2-0-dev \
@@ -44,13 +50,15 @@ RUN set -e -x && apt update && apt upgrade -y && apt install -y \
 
 RUN set -e -x && \
     curl -L $OPENSSL_DOWNLOAD_URL -o openssl.tar.gz && \
-    echo "${OPENSSL_SHA256} ./openssl.tar.gz" | sha256sum -c - && \
+    echo "${OPENSSL_SHA256} *openssl.tar.gz" | sha256sum -c - && \
     curl -L $OPENSSL_PGP_SIG -o openssl.tar.gz.asc && \
-    export GNUPGHOME="$(mktemp -d)" && \
+    gpg --no-tty --keyserver keys.openpgp.org --recv-keys $OPENSSL_GPG_PUBKEY $MATT_CASWELL $RICHARD_LEVITTE $TOMAS_MRAZ $PAUL_DALE && \
     gpg --verify openssl.tar.gz.asc openssl.tar.gz && \
-    tar xf openssl.tar.gz && \
-    cd $OPENSSL_VERSION && \
-    ./config \
+    tar xf openssl.tar.gz
+
+RUN ls -hal
+
+RUN cd openssl-$OPENSSL_VERSION && ./config \
       --prefix=/opt/openssl \
       --openssldir=/opt/openssl \
       no-weak-ssl-ciphers \
@@ -74,13 +82,13 @@ RUN groupadd -g $GROUP_ID --system $NAME && \
 RUN set -e -x && \
     curl -sSL $UNBOUND_DOWNLOAD_URL -o unbound.tar.gz && \
     echo "${UNBOUND_SHA256} *unbound.tar.gz" | sha256sum -c - && \
-    curl -L ${UNBOUND_PGP_SIG} -o openssl.tar.gz.asc && \
-    gpg --verify openssl.tar.gz.asc unbound.tar.gz && \
+    curl -L ${UNBOUND_PGP_SIG} -o unbound-${UNBOUND_VERSION}.tar.gz.asc && \
+    gpg --keyserver keys.openpgp.org --recv-keys EDFAA3F2CA4E6EB05681AF8E9F6F1C2D7E045F8D && \
+    gpg --verify unbound-${UNBOUND_VERSION}.tar.gz.asc unbound.tar.gz && \
     tar xzf unbound.tar.gz && \
-    rm -f unbound.tar.gz && \
-    cd unbound-${UNBOUND_VERSION} && \
-    groupadd -g $GROUP_ID --system $NAME && \
-    useradd -u $USER_ID --gid $GROUP_ID -g $NAME --system -d /etc/unbound $NAME && \
+    rm -f unbound.tar.gz
+
+RUN cd unbound-${UNBOUND_VERSION} && \
     ./configure \
         --disable-dependency-tracking \
         --with-pthreads \
@@ -93,23 +101,28 @@ RUN set -e -x && \
         --enable-tfo-client \
         --enable-event-api \
         --enable-subnet && \
-    make install && \
-    rm -rf \
+        make install
+
+RUN mkdir -p /usr/share/dns
+COPY root/root.* /usr/share/dns/
+RUN chmod 777 /usr/share/dns && chmod 666 /usr/share/dns/*
+RUN mkdir -p /opt/unbound/log && chmod 777 /opt/unbound/log
+
+RUN rm -rf \
         /opt/unbound/share/man \
         /tmp/* \
         /var/tmp/* \
         /var/lib/apt/lists/*
 
-WORKDIR /etc/unbound
+RUN set -x && apt purge -y --auto-remove build-essential curl
+RUN mv /usr/local/etc/unbound/unbound.conf /usr/local/etc/unbound/unbound.conf.bak
+COPY docker_files/unbound.conf /usr/local/etc/unbound/unbound.conf
+COPY docker_files/a-records.conf /usr/local/etc/unbound/a-records.conf
+COPY docker_files/srv-records.conf /usr/local/etc/unbound/srv-records.conf
+COPY docker_files/forward-records.conf /usr/local/etc/unbound/forward-records.conf
+RUN rm -rf /usr/local/etc/unbound/unbound.conf.d/*
 
-RUN set -x && apt purge -y --auto-remove $BUILD_DEPS
-RUN mv /etc/unbound/unbound.conf /etc/unbound/unbound.conf.bak
-COPY docker_files/unbound.conf /etc/unbound/unbound.conf
-COPY docker_files/a-records.conf /etc/unbound/a-records.conf
-COPY docker_files/srv-records.conf /etc/unbound/srv-records.conf
-COPY docker_files/forward-records.conf /etc/unbound/forward-records.conf
-RUN rm -rf /etc/unbound/unbound.conf.d/*
-RUN chown -R $NAME:$NAME /etc/unbound
+WORKDIR /var/log/unbound/
 
 #LABEL org.opencontainers.image.version=${UNBOUND_VERSION} \
 #      org.opencontainers.image.title="vmikhailov/unbound" \
@@ -124,6 +137,6 @@ EXPOSE 53/udp
 EXPOSE 853/tcp
 EXPOSE 853/udp
 
-HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=3 CMD drill @127.0.0.1 cloudflare.com || exit 1
+#HEALTHCHECK --interval=30s --timeout=30s --start-period=10s --retries=3 CMD drill @127.0.0.1 cloudflare.com || exit 1
 
-CMD ["/usr/sbin/unbound", "-c", "/etc/unbound/unbound.conf"]
+CMD ["/usr/local/sbin/unbound", "-c", "/usr/local/etc/unbound/unbound.conf"]
